########################################################################
# WEBSITE https://flowork.cloud
# File NAME : C:\FLOWORK\tools\article_generator_tools\processor.py total lines 86 
########################################################################

from flowork_kernel.api_contract import BaseModule, IExecutable, IDataPreviewer
from flowork_kernel.utils.payload_helper import get_nested_value
from flowork_kernel.api_client import ApiClient

class ArticleGeneratorModule(BaseModule, IExecutable, IDataPreviewer):

    TIER = "pro"

    def __init__(self, module_id, services):
        super().__init__(module_id, services)
        self.api_client = ApiClient(kernel=self.kernel)
        self.ai_manager = self.services.get("ai_provider_manager_service")

    def execute(self, payload: dict, config: dict, status_updater, mode='EXECUTE', **kwargs):
        provider_id = config.get('selected_ai_provider', 'openai_gpt4')
        prompt_config_value = config.get('prompt_source_variable', 'data.optimal_prompt')

        prompt_text = None

        if isinstance(prompt_config_value, dict):
            prompt_text = prompt_config_value.get('content') or prompt_config_value.get('prompt_text')

        elif isinstance(prompt_config_value, str):
            prompt_text = get_nested_value(payload, prompt_config_value)

            if not prompt_text:
                prompt_text = prompt_config_value

        if not prompt_text:
             prompt_text = get_nested_value(payload, 'data.prompt') or get_nested_value(payload, 'data.prompt_artikel')

        if mode == 'SIMULATE':
            status_updater("Simulating article generation...", "INFO")
            return {"payload": payload, "output_name": "success"}

        try:
            status_updater(f"Generating article using {provider_id}...", "processing")

            if not prompt_text:
                raise Exception("Prompt text is empty. Please select a template or provide a valid variable path.")

            response = self.ai_manager.query_ai_by_task('text', prompt_text, endpoint_id=provider_id)

            if "error" in response:
                raise Exception(response["error"])

            article_text = response.get('data')
            if not article_text:
                raise Exception("AI provider returned empty response.")

            if 'data' not in payload or not isinstance(payload['data'], dict):
                payload['data'] = {}

            payload['data']['article_text'] = article_text

            status_updater("Article generated successfully.", "SUCCESS")
            return {"payload": payload, "output_name": "success"}

        except Exception as e:
            return self._error_payload(payload, f"Generation failed: {str(e)}")

    def _error_payload(self, payload, msg):
        self.logger(msg, "ERROR")
        if 'data' not in payload: payload['data'] = {}
        payload['data']['error'] = msg
        return {"payload": payload, "output_name": "error"}

    def get_dynamic_output_schema(self, config):
        return [{
            "name": "data.article_text",
            "type": "string",
            "description": "The final article text generated by the AI."
        }]

    def get_data_preview(self, config: dict):
        provider = config.get('selected_ai_provider', 'Unknown')
        return [{
            'status': 'info',
            'message': f'Will generate article using {provider}'
        }]
